Description:
    Daniel Salazar | June 2020
    This will create a Bastion Host. The security group's CIDR IP should be changed to the IP of
    the dev computer. This can be used to make changes to servers in private subnets or to
    check logs or whatever.
    
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  
Resources:
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-003634241a8fcdec0 # Ubuntu
      # Ideally you want to only put the key during the time that you execute
      # this script. Remove it immediately after
      # Remember: If you push this, the key name will be public
      KeyName: bastion-key
      SubnetId: 
        Fn::ImportValue:
          !Sub "${EnvironmentName}-PUB1-SN"
      SecurityGroupIds:
        - !Ref BastionHostSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt-get update

  BastionHostSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      # A description for the security group
      # String
      GroupDescription: Allow ssh to/from our bastion host
      # The name of the security group
      # GroupName: String
      # The inbound rules associated with the security group
      SecurityGroupIngress: 
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0 # Change this to my IP Address
      # Any tags assigned to the security group
      #Tags: 
      #  - Tag
      # The ID of the VPC for the security group
      # String
      VpcId: 
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"

Outputs:
  BastionIP:
    Description: The Public IP Address of the basion host
    Value:  !GetAtt [BastionHost, PublicIp]
    Export:
      Name: !Sub ${EnvironmentName}-B-IP