  Parameters:
    IAMPassword:
      NoEcho: 'true'
      Type: String
      Description: New account password
      MinLength: '1'
      MaxLength: '41'
      ConstraintDescription: the password must be between 1 and 41 characters

  KubeIAMPassword:
    NoEcho: 'true'
    Type: String
    Description: New account password
    MinLength: '1'
    MaxLength: '41'
    ConstraintDescription: the password must be between 1 and 41 characters

Resources:
  JenkinsIAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Groups:
        - !Ref JenkinsIAMGroup
      # The friendly name (not ARN) identifying the policy
      PolicyName: JenkinsIAMUsers
      # Adds full access to S3
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action: s3:*
          Resource: '*'
        - Effect: Allow
          Action: rds:*
          Resource: '*'
        - Effect: Allow
          Action: lambda:*
          Resource: '*'

  JenkinsIAMUser:
    Type: AWS::IAM::User
    Properties:
        # Creates a password for the specified user, giving the user the
        # ability to access AWS services through the AWS Management Console
        LoginProfile:
            Password: !Ref 'IAMPassword'
    
  JenkinsIAMGroup:
    Type: AWS::IAM::Group

  JenkinsIAMUsers:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
        # The name of the group to update
        GroupName: !Ref 'JenkinsIAMGroup'
        # A list of the names of the users that you want to add to the group
        Users: 
        - !Ref 'JenkinsIAMUser'

  JenkinsIAMKeys:
    Type: AWS::IAM::AccessKey
    Properties:
        UserName: !Ref 'JenkinsIAMUser'

  KubeIAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Groups:
        - !Ref KubeIAMGroup
      # The friendly name (not ARN) identifying the policy
      PolicyName: KubeIAMUsers
      # Adds full access to S3
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action: s3:*
          Resource: '*'
        - Effect: Allow
          Action: iam:*
          Resource: '*'
        - Effect: Allow
          Action: route53:*
          Resource: '*'
        - Effect: Allow
          Action: ec2:*
          Resource: '*'

  KubeIAMUser:
    Type: AWS::IAM::User
    Properties:
      # Creates a password for the specified user, giving the user the
      # ability to access AWS services through the AWS Management Console
      LoginProfile:
          Password: !Ref 'KubeIAMPassword'
    
  KubeIAMGroup:
    Type: AWS::IAM::Group

  KubeIAMUsers:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      # The name of the group to update
      GroupName: !Ref 'KubeIAMGroup'
      # A list of the names of the users that you want to add to the group
      Users: 
      - !Ref 'KubeIAMUser'

  KubeIAMKeys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'KubeIAMUser'

Outputs:
  JenkinsAccessKey:
    Value: !Ref 'JenkinsIAMKeys'
    Description: AWSAccessKeyId of  user
  JenkinsSecretKey:
    Value: !GetAtt [JenkinsIAMKeys, SecretAccessKey]
    Description: AWSSecretAccessKey of  user
  KubeAccessKey:
    Value: !Ref 'KubeIAMKeys'
    Description: AWSAccessKeyId of  user
  KubeSecretKey:
    Value: !GetAtt [KubeIAMKeys, SecretAccessKey]
    Description: AWSSecretAccessKey of  user